// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package sqlc

import (
	"context"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
  name,
  address,
  contact_number
) VALUES (
  $1, $2, $3
) RETURNING id, name, address, contact_number, created_at, updated_at
`

type CreateCustomerParams struct {
	Name          string `json:"name"`
	Address       string `json:"address"`
	ContactNumber string `json:"contact_number"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer, arg.Name, arg.Address, arg.ContactNumber)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ContactNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customers WHERE id = $1
`

func (q *Queries) DeleteCustomer(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCustomer, id)
	return err
}

const getAllCustomers = `-- name: GetAllCustomers :many
SELECT id, name, address, contact_number, created_at, updated_at FROM customers
ORDER BY name
`

func (q *Queries) GetAllCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.Query(ctx, getAllCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.ContactNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomerById = `-- name: GetCustomerById :one
SELECT id, name, address, contact_number, created_at, updated_at FROM customers WHERE id = $1
`

func (q *Queries) GetCustomerById(ctx context.Context, id int32) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerById, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ContactNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers SET
  name = $2,
  address = $3,
  contact_number = $4,
  updated_at = NOW()
WHERE id = $1
RETURNING id, name, address, contact_number, created_at, updated_at
`

type UpdateCustomerParams struct {
	ID            int32  `json:"id"`
	Name          string `json:"name"`
	Address       string `json:"address"`
	ContactNumber string `json:"contact_number"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.ContactNumber,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ContactNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
