// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  name,
  description,
  cost_price_cents,
  selling_price_cents,
  quantity_on_hand,
  low_stock_threshold,
  category_id,
  is_active
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, name, description, cost_price_cents, selling_price_cents, quantity_on_hand, low_stock_threshold, category_id, is_active, created_at, updated_at
`

type CreateProductParams struct {
	Name              string      `json:"name"`
	Description       string      `json:"description"`
	CostPriceCents    int32       `json:"cost_price_cents"`
	SellingPriceCents int32       `json:"selling_price_cents"`
	QuantityOnHand    int32       `json:"quantity_on_hand"`
	LowStockThreshold int32       `json:"low_stock_threshold"`
	CategoryID        pgtype.Int4 `json:"category_id"`
	IsActive          bool        `json:"is_active"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.CostPriceCents,
		arg.SellingPriceCents,
		arg.QuantityOnHand,
		arg.LowStockThreshold,
		arg.CategoryID,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CostPriceCents,
		&i.SellingPriceCents,
		&i.QuantityOnHand,
		&i.LowStockThreshold,
		&i.CategoryID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT id, name, description, cost_price_cents, selling_price_cents, quantity_on_hand, low_stock_threshold, category_id, is_active, created_at, updated_at FROM products
ORDER BY name
`

func (q *Queries) GetAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CostPriceCents,
			&i.SellingPriceCents,
			&i.QuantityOnHand,
			&i.LowStockThreshold,
			&i.CategoryID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductById = `-- name: GetProductById :one
SELECT id, name, description, cost_price_cents, selling_price_cents, quantity_on_hand, low_stock_threshold, category_id, is_active, created_at, updated_at FROM products WHERE id = $1
`

func (q *Queries) GetProductById(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRow(ctx, getProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CostPriceCents,
		&i.SellingPriceCents,
		&i.QuantityOnHand,
		&i.LowStockThreshold,
		&i.CategoryID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products SET
  name = $2,
  description = $3,
  cost_price_cents = $4,
  selling_price_cents = $5,
  quantity_on_hand = $6,
  low_stock_threshold = $7,
  category_id = $8,
  is_active = $9,
  updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, cost_price_cents, selling_price_cents, quantity_on_hand, low_stock_threshold, category_id, is_active, created_at, updated_at
`

type UpdateProductParams struct {
	ID                int32       `json:"id"`
	Name              string      `json:"name"`
	Description       string      `json:"description"`
	CostPriceCents    int32       `json:"cost_price_cents"`
	SellingPriceCents int32       `json:"selling_price_cents"`
	QuantityOnHand    int32       `json:"quantity_on_hand"`
	LowStockThreshold int32       `json:"low_stock_threshold"`
	CategoryID        pgtype.Int4 `json:"category_id"`
	IsActive          bool        `json:"is_active"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CostPriceCents,
		arg.SellingPriceCents,
		arg.QuantityOnHand,
		arg.LowStockThreshold,
		arg.CategoryID,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CostPriceCents,
		&i.SellingPriceCents,
		&i.QuantityOnHand,
		&i.LowStockThreshold,
		&i.CategoryID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
