// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vendors.sql

package sqlc

import (
	"context"
)

const createVendor = `-- name: CreateVendor :one
INSERT INTO vendors (
  name,
  address,
  contact_person,
  contact_number
) VALUES (
  $1, $2, $3, $4
) RETURNING id, name, address, contact_person, contact_number, created_at, updated_at
`

type CreateVendorParams struct {
	Name          string `json:"name"`
	Address       string `json:"address"`
	ContactPerson string `json:"contact_person"`
	ContactNumber string `json:"contact_number"`
}

func (q *Queries) CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, createVendor,
		arg.Name,
		arg.Address,
		arg.ContactPerson,
		arg.ContactNumber,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ContactPerson,
		&i.ContactNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVendor = `-- name: DeleteVendor :exec
DELETE FROM vendors WHERE id = $1
`

func (q *Queries) DeleteVendor(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteVendor, id)
	return err
}

const getAllVendors = `-- name: GetAllVendors :many
SELECT id, name, address, contact_person, contact_number, created_at, updated_at FROM vendors
ORDER BY name
`

func (q *Queries) GetAllVendors(ctx context.Context) ([]Vendor, error) {
	rows, err := q.db.Query(ctx, getAllVendors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vendor{}
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.ContactPerson,
			&i.ContactNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVendorById = `-- name: GetVendorById :one
SELECT id, name, address, contact_person, contact_number, created_at, updated_at FROM vendors WHERE id = $1
`

func (q *Queries) GetVendorById(ctx context.Context, id int32) (Vendor, error) {
	row := q.db.QueryRow(ctx, getVendorById, id)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ContactPerson,
		&i.ContactNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVendor = `-- name: UpdateVendor :one
UPDATE vendors SET
  name = $2,
  address = $3,
  contact_person = $4,
  contact_number = $5,
  updated_at = NOW()
WHERE id = $1
RETURNING id, name, address, contact_person, contact_number, created_at, updated_at
`

type UpdateVendorParams struct {
	ID            int32  `json:"id"`
	Name          string `json:"name"`
	Address       string `json:"address"`
	ContactPerson string `json:"contact_person"`
	ContactNumber string `json:"contact_number"`
}

func (q *Queries) UpdateVendor(ctx context.Context, arg UpdateVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, updateVendor,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.ContactPerson,
		arg.ContactNumber,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ContactPerson,
		&i.ContactNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
