CREATE TABLE IF NOT EXISTS customers(
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE CHECK (name <> ''),
  address TEXT NOT NULL DEFAULT '',
  contact_number VARCHAR(12) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
